version: "3"

services:
  db:
    build:
      context: ./DockerPostgresql
      dockerfile: db.Dockerfile
    container_name: db
    hostname: db
    environment:
      POSTGRES_USER: ntt_data
      POSTGRES_DB: banco_ntt
      POSTGRES_PASSWORD: ntt_data
    ports:
      - "5432:5432"
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8082:8082
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db